[pytest]
asyncio_mode = strict
pythonpath = .
log_cli = true
log_cli_level = INFO

filterwarnings =
    ignore:.*allowed_objects.*
    ignore:.*iscoroutinefunction.*
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::ResourceWarning
    ignore::UserWarning
    ignore:.*UnionGenericAlias.*
    ignore:.*Core Pydantic V1 functionality.*
    ignore:.*jsonschema.*
    ignore:.*google.genai.*
    ignore:.*langchain.*

addopts =
    --cov=core
    --cov=verticals
    --cov=shims
    --cov=frameworks
    --cov-report=term-missing
    --cov-report=html
    --no-cov
